version: '3.8'
services:
  redis:
    image: redis:alpine
  
  api_service:
    build: ./api_service
    ports:
      - "5000:5000"
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis

  worker_service:
    build: ./worker_service
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis

  realtime_service:
    build: 
      context: .
      dockerfile: ./api_service/Dockerfile # Reuse API Dockerfile for python env
    command: python websocket_server.py
    ports:
      - "8080:8080"
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis